
-- drop table if exists ESRD_clean_raw.medical_claims;
create table ESRD_clean_raw.medical_claims
(
	ClaimNumber	varchar(50),
	AdjustedClaim	varchar(50),
	ClaimStatus	varchar(15),
	ClaimType	varchar(1),
	CheckNumber	varchar(20),
	CheckDate	date,
	ProcessedDate	date,
	ReceivedDate	date,
	MemberID	varchar(20),
	CoveredIndividualID	varchar(20),
	AdmitDate	date,
	AdmissionHour	varchar(2),
	AdmissionSource	varchar(2),
	AdmitType	varchar(2),
	DischargeDate	date,
	DischargeHour 	varchar(2),
	DischargeStatus	varchar(10),
	Account_Plan_GroupID	varchar(30),
	TypeOfBill	varchar(4),
	InvoiceNumber	varchar(100),
	ClaimSubmittedChargeAmount	numeric(10,2),
	ClaimDisallowedAmount	numeric(10,2),
	DisallowedReason1	varchar(100),
	DisallowedReason2	varchar(100),
	DisallowedReason3	varchar(100),
	ClaimAllowedAmount	numeric(10,2),
	ClaimPaidAmount	numeric(10,2),
	ICD_10Indicator	varchar(1),
	PrincipalProcedureCode	varchar(10),
	PrincipalProcedureDate	date,
	ICDProcedureCode2	varchar(10),
	ICDProcedureDate2	date,
	ICDProcedureCode3	varchar(10),
	ICDProcedureDate3	date,
	ICDProcedureCode4	varchar(10),
	ICDProcedureDate4	date,
	ICDProcedureCode5	varchar(10),
	ICDProcedureDate5	date,
	ICDProcedureCode6	varchar(10),
	ICDProcedureDate6	date,
	CPTCode1	varchar(10),
	CPT1Date	date,
	CPTCode2	varchar(10),
	CPT2Date	date,
	CPTCode3	varchar(10),
	CPT3Date	date,
	CPTCode4	varchar(10),
	CPT4Date	date,
	CPTCode5	varchar(10),
	CPT5Date	date,
	AdmittingDXCode	varchar(10),
	PrimaryDXCode	varchar(10),
	DXCode2	varchar(10),
	DXCode3	varchar(10),
	DXCode4	varchar(10),
	DXCode5	varchar(10),
	DXCode6	varchar(10),
	DXCode7	varchar(10),
	DXCode8	varchar(10),
	DXCode9	varchar(10),
	DXCode10	varchar(10),
	DXCode11 	varchar(10),
	DXCode12	varchar(10),
	DXCode13	varchar(10),
	DXCode14	varchar(10),
	DXCode15	varchar(10),
	DXCode16	varchar(10),
	DXCode17	varchar(10),
	DXCode18	varchar(10),
	DXCode19	varchar(10),
	DXCode20	varchar(10),
	DXCode21	varchar(10),
	DXCode22	varchar(10),
	DXCode23	varchar(10),
	DXCode24	varchar(10),
	DXCode25	varchar(10),
	DXCode26	varchar(10),
	DXCode27	varchar(10),
	DXCode28	varchar(10),
	DXCode29	varchar(10),
	DXCode30	varchar(10),
	DXCode31	varchar(10),
	DXCode32	varchar(10),
	DXCode33	varchar(10),
	DXCode34	varchar(10),
	DXCode35	varchar(10),
	DXCode36	varchar(10),
	DXCode37	varchar(10),
	DXCode38	varchar(10),
	DXCode39	varchar(10),
	DXCode40	varchar(10),
	DRGCode	varchar(10),
	DRGVersion	varchar(20),
	DateOfAccident	date,
	EmergencyRoomFlag	varchar(1),
	MVAFlag	varchar(1),
	WorkCompFlag	varchar(1),
	AccidentFlag	varchar(1),
	AccidentState	varchar(2),
	AccidentHour	varchar(2),
	InNetwork_OutofNetworkIndicator	varchar(1),
	ReferringProviderIdentifier	varchar(15),
	BillingProviderIdentifier	varchar(15),
	ProviderPatientAccountNumber	varchar(30),
	MedicalRecordNumber	varchar(30),
	OccurrenceCode1	varchar(2),
	OccurrenceCode1Date	date,
	OccurrenceCode2	varchar(2),
	OccurrenceCode2Date	date,
	OccurrenceCode3	varchar(2),
	OccurrenceCode3Date	date,
	OccurrenceCode4	varchar(2),
	OccurrenceCode4Date	date,
	OccurrenceSpanCode1 varchar(2),
	OccurrenceSpanFromDate1	date,
	OccurrenceSpanToDate1	date,
	OccurrenceSpanCode2	varchar(2),
	OccurrenceSpanFromDate2	date,
	OccurrenceSpanToDate2	date,
	ConditionCode1	varchar(2),
	ConditionCode2	varchar(2),
	ConditionCode3	varchar(2),
	ConditionCode4	varchar(2),
	ConditionCode5	varchar(2),
	ConditionCode6	varchar(2),
	ConditionCode7	varchar(2),
	ConditionCode8	varchar(2),
	ConditionCode9	varchar(2),
	ConditionCode10	varchar(2),
	ConditionCode11	varchar(2),
	ConditionCode12	varchar(2),
	ValueCode1	varchar(2),
	ValueCode1Amount	numeric(10,2),
	ValueCode2	varchar(2),
	ValueCode2Amount	numeric(10,2),
	ValueCode3	varchar(2),
	ValueCode3Amount	numeric(10,2),
	ValueCode4	varchar(2),
	ValueCode4Amount	numeric(10,2),
	ValueCode5	varchar(2),
	ValueCode5Amount	numeric(10,2),
	ValueCode6	varchar(2),
	ValueCode6Amount	numeric(10,2),
	ValueCode7	varchar(2),
	ValueCode7Amount	numeric(10,2),
	ValueCode8	varchar(2),
	ValueCode8Amount	numeric(10,2),
	ValueCode9	varchar(2),
	ValueCode9Amount	numeric(10,2),
	ValueCode10	varchar(2),
	ValueCode10Amount	numeric(10,2),
	ValueCode11	varchar(2),
	ValueCode11Amount	numeric(10,2),
	ValueCode12	varchar(2),
	ValueCode12Amount	numeric(10,2),
	PayeeCode	varchar(10),
	LineNumber	varchar(15),
	DiagnosisCodePointer1	varchar(2),
	DiagnosisCodePointer2	varchar(2),
	DiagnosisCodePointer3	varchar(2),
	DiagnosisCodePointer4	varchar(2),
	ProcedureCode	varchar(10),
	ProcedureCodeModifier1	varchar(2),
	ProcedureCodeModifier2	varchar(2),
	ProcedureCodeModifier3	varchar(2),
	ProcedureCodeModifier4	varchar(2),
	RevenueCode	varchar(10),
	AccommodationRevenueCode	varchar(10),
	AccommodationRate	varchar(10),
	AncillaryRevenueCode	varchar(10),
	EmergencyIndicator	varchar(1),
	NDCCode	varchar(15),
	DateWritten	date,
	FirstDOS	date,
	LastDOS	date,
	Units	varchar(100),
	Anesthesia	varchar(100),
	ChargeAmount	numeric(10,2),
	AllowedAmount	numeric(10,2),
	NotAllowedAmount	numeric(10,2),
	DeductibleAmount	numeric(10,2),
	CopayAmount	numeric(10,2),
	CoinsuranceAmount	numeric(10,2),
	WouldPayAmount	numeric(10,2),
	BenefitAmount	numeric(10,2),
	ProviderDiscountAmount	numeric(10,2),
	PlaceofService	varchar(2),
	TypeofService	varchar(3),
	PerformingProviderIdentifier	varchar(15),
	COBIndicator	varchar(1),
	COBAmount	numeric(10,2),
	COBPayer	varchar(100),
	COBDate	date,
	CapitatedIndicator	varchar(1),
	Remarks	varchar(100),
	ClaimClientSpecificField1	varchar(50),
	ClaimClientSpecificField2	varchar(50),
	ClaimClientSpecificField3	varchar(50),
	ClaimClientSpecificField4	varchar(50),
	ClaimClientSpecificField5	varchar(50),
	ClaimClientSpecificField6	varchar(50),
	ClaimClientSpecificField7	varchar(50),
	ClaimClientSpecificField8	varchar(50),
	ClaimClientSpecificField9	varchar(50),
	ClaimClientSpecificField10	varchar(50),
	dhp_ch_ldos	date,
	dhp_medclm_load_mo	int,
	dhp_ci_id	varchar(50),
	dhp_s_id	varchar(50),
	dhp_a_id	varchar(100),
	dhp_paid_amt	numeric(10,2),
	dhp_perf_prv_id	varchar(50),
	dhp_bill_prv_id	varchar(50),
	dhp_ch_claim_status_cd	varchar(30),
	dhp_cli_capitated_ind	smallint,
	dhp_ch_emrg_room_ind	smallint,
	dhp_ch_mva_ind	smallint,
	dhp_ch_acc_ind	smallint,
	dhp_ch_amb_ind	smallint,
	dhp_ch_wc_ind	smallint,
	dhp_ch_cob_ind	smallint,
	dhp_check_nbr	int,
	ch_acct1_segment	varchar(50),
	ch_acct2_segment	varchar(50),
	ch_acct3_segment	varchar(50),
	ch_acct4_segment	varchar(50),
	ch_acct5_segment	varchar(50),
	ch_acct_name	varchar(100),
	a_funding_cd	varchar(50),
	cycle_sk	int,
	eic_sk	int,
	cl_sk	int,
	cycle_created_date	timestamp,
	filename	varchar(1000),
	dhp_ch_claim_nbr	varchar(100),
	dhp_ch_clm_line_nbr	varchar(50),
	dhp_claim_form_type	int,
	dhp_charge_amt	numeric(10,2),
	ch_payment_status_cd_sk	int,
	ch_received_date	timestamp,
	eic_extract_dt	timestamp,
	dhp_cli_status_cd	varchar(50),
	dhp_claim_status	varchar(15),
	dhp_proc_code	varchar(10)
)
diststyle	key
distkey(CoveredIndividualID)
interleaved sortkey(ClaimNumber, ICD_10Indicator,FirstDOS,PerformingProviderIdentifier,BillingProviderIdentifier)
;

copy ESRD_clean_raw.medical_claims from 's3://dhp-randlab-s3/multi_tenant_clients/c048_hfny/esrd/clean_raw/medclm_history.txt'
credentials 'aws_iam_role=arn:aws:iam::722648170004:role/administrator_role'
ACCEPTINVCHARS BLANKSASNULL EMPTYASNULL NULL AS 'NULL' IGNOREBLANKLINES IGNOREHEADER 1 TRIMBLANKS DELIMITER '|' STATUPDATE ON MAXERROR 250;

set statement_timeout to 0;

copy ESRD_clean_raw.medical_claims from 's3://dhp-randlab-s3/multi_tenant_clients/c048_hfny/esrd/clean_raw/medclm_history_p'
credentials 'aws_iam_role=arn:aws:iam::722648170004:role/administrator_role'
ACCEPTINVCHARS BLANKSASNULL EMPTYASNULL NULL AS 'NULL' IGNOREBLANKLINES IGNOREHEADER 1 TRIMBLANKS DELIMITER '|' STATUPDATE ON MAXERROR 2000;

vacuum reindex ESRD_clean_raw.medical_claims;
analyze ESRD_clean_raw.medical_claims;


-- drop table if exists ESRD_clean_raw.provider_info;
create table ESRD_clean_raw.provider_info
(
	ProviderID varchar(20),
	ProviderNPI varchar(30),
	ReplacementNPI varchar(100),
	NPIDeactivationDate date,
	NPIDeactivationReason varchar(100),
	NPIReactivationDate date,
	ProviderLicenseNumber varchar(100),
	ProviderLicenseStateCode varchar(100),
	EntityTypeCode varchar(100),
	ProviderName varchar(100),
	ProviderOtherName varchar(100),
	ProviderOrgName varchar(100),
	ProviderTaxID varchar(30),
	ProviderNumber varchar(30),
	MedicareNumber varchar(30),
	ProviderStreet1 varchar(100),
	ProviderStreet2 varchar(100),
	ProviderCity varchar(50),
	ProviderState varchar(2),
	ProviderZipCode varchar(10),
	ProviderPhone1 varchar(20),
	ProviderPhone1extension varchar(10),
	ProviderGenderCode varchar(100),
	AuthorizedOfficialContactName varchar(100),
	Street1 varchar(100),
	Street2 varchar(100),
	AuthorizedOfficialContactProviderCity varchar(50),
	AuthorizedOfficialContactProviderState varchar(2),
	AuthorizedOfficialContactProviderZipCode varchar(10),
	Phone1 varchar(100),
	Phone1Extension varchar(100),
	BillingProviderID varchar(30),
	ProviderFAX varchar(20),
	NetworkAffiliation varchar(100),
	Network varchar(1),
	PCP varchar(1),
	ParNonPar varchar(1),
	HealthcareProviderTaxonomyCode varchar(100),
	OtherProviderIdentifier varchar(100),
	OtherProviderIdentifierTypeCode varchar(100),
	ProviderEnumerationDate date,
	ProviderEmailAddress varchar(50),
	PrimarySpecialty varchar(10),
	SecondarySpecialty varchar(10),
	LastUpdateDate date,
	ProviderClientSpecificField1 varchar(50),
	ProviderClientSpecificField2 varchar(50),
	ProviderClientSpecificField3 varchar(50),
	ProviderClientSpecificField4 varchar(50),
	ProviderClientSpecificField5 varchar(50),
	ProviderClientSpecificField6 varchar(50),
	ProviderClientSpecificField7 varchar(50),
	ProviderClientSpecificField8 varchar(50),
	ProviderClientSpecificField9 varchar(50),
	ProviderClientSpecificField10 varchar(50),
	dhp_prv_nbr varchar(50),
	dhp_prv_name varchar(100),
	dhp_state_cd varchar(50),
	dhp_state_cd_sk int,
	cycle_sk int,
	eic_sk int,
	cl_sk int,
	cycle_created_date timestamp,
	filename varchar(1000),
	dhp_tax_id varchar(50)
)
diststyle even
interleaved sortkey(ProviderID,ProviderNPI)
;

vacuum reindex ESRD_clean_raw.provider_info;
analyze ESRD_clean_raw.provider_info;

copy ESRD_clean_raw.provider_info from 's3://dhp-randlab-s3/multi_tenant_clients/c048_hfny/esrd/clean_raw/tmp/prv_history.psv'
credentials 'aws_iam_role=arn:aws:iam::722648170004:role/administrator_role'
ACCEPTINVCHARS BLANKSASNULL EMPTYASNULL IGNOREBLANKLINES IGNOREHEADER 1 TRIMBLANKS DELIMITER '|' STATUPDATE ON MAXERROR 25;

copy ESRD_clean_raw.provider_info from 's3://dhp-randlab-s3/multi_tenant_clients/c048_hfny/esrd/clean_raw/prv_history.txt'
credentials 'aws_iam_role=arn:aws:iam::722648170004:role/administrator_role'
ACCEPTINVCHARS BLANKSASNULL EMPTYASNULL IGNOREBLANKLINES IGNOREHEADER 1 TRIMBLANKS DELIMITER '|' STATUPDATE ON MAXERROR 25;

-- drop table if exists ESRD_clean_raw.member_info;
create table ESRD_clean_raw.member_info
(
	MemberID varchar(20),
	FamilyID varchar(10),
	CoveredIndividualsFamilyIDSuffix varchar(10),
	CoveredIndividualID varchar(20),
	CoveredIndividualSSN varchar(15),
	CoveredIndividualHICN varchar(15),
	CoveredIndividualAlternateID varchar(20),
	COBFlag varchar(1),
	COBCompany varchar(100),
	COBPolicyNumber varchar(50),
	COBLetterDate date,
	COBEligibilityStartDate date,
	COBEligibilityEndDate date,
	CoveredIndividualRelationToMember varchar(6),
	CoveredIndividualFirstName varchar(25),
	CoveredIndividualMiddleName varchar(25),
	CoveredIndividualLastName varchar(50),
	CoveredIndividualStreet1 varchar(100),
	CoveredIndividualStreet2 varchar(100),
	CoveredIndividualCity varchar(50),
	CoveredIndividualState varchar(2),
	CoveredIndividualZipCode varchar(15),
	CoveredIndividualPhone1 varchar(20),
	CoveredIndividualPhone1Extension varchar(10),
	CoveredIndividualPhone2 varchar(20),
	CoveredIndividualPhone2Extension varchar(10),
	CoveredIndividualEmail varchar(100),
	CoveredIndividualGender varchar(1),
	CoveredIndividualDateOfBirth date,
	CoveredIndividualDateOfDeath date,
	CoveredIndividualHIPAAIndicator varchar(1),
	CoveredIndividualSpecialHandling varchar(1),
	AccountPlanGroupID varchar(30),
	CoveredIndividualEffectiveDate date,
	CoveredIndividualTerminationDate date,
	TypeofCoverage varchar(1),
	CoverageElection varchar(1),
	EmployeeStatus varchar(1),
	PCP varchar(15),
	AlternateAddressName varchar(75),
	AlternateAddress1 varchar(100),
	AlternateAddress2 varchar(100),
	AlternateCity varchar(50),
	AlternateState varchar(2),
	AlternateZipCode varchar(10),
	AlternatePhone1 varchar(20),
	AlternatePhone1Ext varchar(10),
	AlternatePhone2 varchar(20),
	AlternatePhone2Ext varchar(10),
	AlternateBeginDate date,
	AlternateEndDate date,
	PrivateAddressName varchar(75),
	PrivateAddress1 varchar(100),
	PrivateAddress2 varchar(100),
	PrivateCity varchar(50),
	PrivateState varchar(2),
	PrivateZipCode varchar(10),
	PrivatePhone1 varchar(20),
	PrivatePhone1Ext varchar(10),
	PrivatePhone2 varchar(20),
	PrivatePhone2Ext varchar(10),
	PrivateBeginDate date,
	PrivateEndDate date,
	MembershipClientSpecificField1 varchar(50),
	MembershipClientSpecificField2 varchar(50),
	MembershipClientSpecificField3 varchar(50),
	MembershipClientSpecificField4 varchar(50),
	MembershipClientSpecificField5 varchar(50),
	MembershipClientSpecificField6 varchar(50),
	MembershipClientSpecificField7 varchar(50),
	MembershipClientSpecificField8 varchar(50),
	MembershipClientSpecificField9 varchar(50),
	MembershipClientSpecificField10 varchar(50),
	MBR_PERS_PART_KEY smallint,
	xfrm_subs_fk_err_ind smallint,
	xfrm_err_dup_err_ind smallint,
	xfrm_rel_cd_err_ind smallint,
	xfrm_sex_cd_err_ind smallint,
	xfrm_state_cd_err_ind smallint,
	dhp_eff_dt date,
	dhp_term_dt date,
	dhp_rel_cd varchar(50),
	dhp_sex_cd varchar(50),
	dhp_state_cd varchar(50),
	dhp_rel_cd_sk int,
	dhp_sex_cd_sk int,
	dhp_state_cd_sk int,
	dhp_dob date,
	cycle_sk int,
	eic_sk int,
	cl_sk int,
	cycle_created_date timestamp,
	filename varchar(1000),
	dhp_dod date,
	dhp_hipaa_ind int,
	dhp_CoveredIndividualSSN varchar(9),
	dhp_CoveredIndividualZipCode varchar(5)
)
diststyle key
distkey(CoveredIndividualID)
interleaved sortkey(CoveredIndividualHICN,CoveredIndividualEffectiveDate,CoveredIndividualTerminationDate)
;

copy ESRD_clean_raw.member_info from 's3://dhp-randlab-s3/multi_tenant_clients/c048_hfny/esrd/clean_raw/tmp/mbr_history.psv'
credentials 'aws_iam_role=arn:aws:iam::722648170004:role/administrator_role'
ACCEPTINVCHARS BLANKSASNULL EMPTYASNULL NULL AS 'NULL' IGNOREBLANKLINES IGNOREHEADER 1 TRIMBLANKS DELIMITER '|' STATUPDATE ON MAXERROR 25 NOLOAD;

copy ESRD_clean_raw.member_info from 's3://dhp-randlab-s3/multi_tenant_clients/c048_hfny/esrd/clean_raw/mbr_history.txt'
credentials 'aws_iam_role=arn:aws:iam::722648170004:role/administrator_role'
ACCEPTINVCHARS BLANKSASNULL EMPTYASNULL NULL AS 'NULL' IGNOREBLANKLINES IGNOREHEADER 1 TRIMBLANKS DELIMITER '|' STATUPDATE ON MAXERROR 25 NOLOAD;

vacuum reindex ESRD_clean_raw.member_info;
analyze ESRD_clean_raw.member_info;


-- drop table if exists ESRD_clean_raw.mmr;
create table ESRD_clean_raw.mmr
(
	mmro_sk	int,
	created_by	int,
	created_date	datetime,
	modified_by	int,
	modified_date	datetime,
	mspc_sk	int,
	mco_contract_number	varchar(5),
	run_file_date	datetime,
 	payment_date	datetime,					/**/
	hicn	varchar(12),						/**/
	surname	varchar(7),							/**/
	first_initial	varchar(1),
	sex	varchar(1),								/**/
	birth_date	datetime,						/**/
	age_group	varchar(4),
	county_code	varchar(5),
	out_area_indicator	varchar(1),
	parta_entitlement	varchar(1),
	partb_entitlement	varchar(1),
	hospice	varchar(1),							/**/
	esrd	varchar(1),							/**/
	msp_aged_disabled	varchar(1),
	institutional	varchar(1),
	nhc	varchar(1),
	new_medicaid_status	varchar(1),
	lti_flag	varchar(1),
	medicaid_indicator	varchar(1),
	pip_dcg	varchar(2),
	risk_factor_code	varchar(1),
	risk_adjuster_factora	varchar(7),
	risk_adjuster_factorb	varchar(7),
	paymt_adjustmt_month_total_parta	varchar(2),
	paymt_adjustmt_month_total_partb	varchar(2),
	adjustmt_reason_code	varchar(2),			/**/
	msapaymt_adjustmt_start_date	datetime,
	msapaymt_adjustmt_end_date	datetime,
	demogrpaymt_adjustmt_amounta	varchar(9),
	demogrpaymt_adjustmt_amountb	varchar(9),
 	lis_premium_subsidy	varchar(8),
	esrd_msp_flag	varchar(1),
	msadeposit_recovery_parta	varchar(8),
	msadeposit_recovery_partb	varchar(8),
	msadeposit_recovery_months	varchar(2),
	current_medicaid_status	varchar(1),
	risk_adjuster_agegroup_raag	varchar(4),
	previous_disable_ratio_prdib	varchar(7),
	de_minimis	varchar(1),
	beneficiary_dualand_partd_enrollment_status	varchar(1),
	plan_benefit_packageid	varchar(3),
	race_code	varchar(1),
	rafactor_type_code	varchar(2),
	frailty_indicator	varchar(1),
	original_reason_entitlement_code_orec	varchar(1),
	lag_indicator	varchar(1),
	segment_id	varchar(3),
	enrollment_source	varchar(1),
	eghp_flag	varchar(1),
	partc_basic_premium_parta_amount	varchar(8),
	partc_basic_premium_partb_amount	varchar(8),
	rebate_parta_costsharing_reduction	varchar(8),
	rebate_partb_costsharing_reduction	varchar(8),
	rebate_otherparta_mandatory_supplemental_benefits	varchar(8),
	rebate_otherpartb_mandatory_supplemental_benefits	varchar(8),
	rebate_partb_premium_reduction_parta_amount	varchar(8),
	rebate_partb_premium_reduction_partb_amount	varchar(8),
	rebate_partd_supplemental_benefits_parta_amount	varchar(8),
	rebate_partd_supplemental_benefits_partb_amount	varchar(8),
	parta_ma_paymt_total	varchar(10),
	partb_ma_paymt_total	varchar(10),
	ma_paymt_total	varchar(11),
	partd_ra_factor	varchar(7),
	partd_lowincome_indicator	varchar(1),
	partd_lowincome_multiplier	varchar(7),
	partd_longterm_institutional_indicator	varchar(1),
	partd_longterm_institutional_multiplier	varchar(7),
	rebate_partd_basicpremium_reduction	varchar(8),
	partd_basicpremium_amount	varchar(8),
	partd_direct_subsidy_monthly_amount	varchar(10),
	reinsurance_subsidy_amount	varchar(10),
	lowincome_subsidy_costsharing_amount	varchar(10),
	partd_payment_total	varchar(11),
	paymt_adjustmt_months_partd	varchar(2),
	pace_premium_addon	varchar(10),
	pace_cost_sharing_addon	varchar(10),
	partc_frailty_score_factor	varchar(7),
	msp_factor	varchar(7),
	msp_reduction_adjustment_amount_parta	varchar(10),
	msp_reduction_adjustment_amount_partb	varchar(10),
	medicaid_dual_status_code	varchar(2),
	partd_coveragegap_discount_amount	varchar(8),
	partd_ra_factor_type	varchar(2),
	partd_risk_factor_code	varchar(1),
	parta_risk_adjusted_monthly_rate_pymt_adj	varchar(9),
	partb_risk_adjusted_monthly_rate_pymt_adj	varchar(9),
	partd_risk_adjusted_monthly_rate_pymt_adj	varchar(9),
	mmro_isAnticipatedAdj	boolean,
	hm_sk	int
)
diststyle	even
interleaved	sortkey(hicn,payment_date,esrd,adjustmt_reason_code)
;
copy ESRD_clean_raw.mmr from 's3://dhp-randlab-s3/multi_tenant_clients/c048_hfny/esrd/clean_raw/mmr_original.txt'
credentials 'aws_iam_role=arn:aws:iam::722648170004:role/administrator_role'
ACCEPTINVCHARS BLANKSASNULL EMPTYASNULL NULL AS 'NULL' IGNOREBLANKLINES IGNOREHEADER 1 TRIMBLANKS DELIMITER '|' STATUPDATE ON MAXERROR 250 NOLOAD;

analyze ESRD_clean_raw.mmr;